export default {
  // User
  FETCH_USER: 'USERS/FETCH_USER',
  LOGIN_USER: 'USERS/LOGIN_USER',
  REGISTER_USER: 'USERS/REGISTER_USER',
  LOGOUT_USER: 'USERS/LOGOUT_USER',
  // Game
  FETCH_GAMES: 'GAME/FETCH_GAMES',
  GAME_DETAIL: 'GAME/FETCH_GAME',
  // Topics
  FETCH_TOPICS: 'GAME/FETCH_TOPICS'
}
