export default {
  // User
  FETCH_USER: 'USERS/FETCH_USER',
  LOGIN_USER: 'USERS/LOGIN_USER',
  REGISTER_USER: 'USERS/REGISTER_USER',
  EDIT_USER: 'USERS/EDIT_USER',
  LOGOUT_USER: 'USERS/LOGOUT_USER',
  USER_ADDCHILD: 'USERS/USER_ADDCHILD',
  // Game
  FETCH_GAMES: 'GAME/FETCH_GAMES',
  // Topics
  FETCH_TOPICS: 'GAME/FETCH_TOPICS',
  // SCHOOLCLASS
  FETCH_SCHOOLCLASS: 'SCHOOLCLASS/FETCH_SCHOOLCLASS'
}
