export default {
  // User
  SET_USERS: 'USERS/SET_USERS',
  SET_AUTHUSER: 'USERS/SET_AUTHUSER',
  LOGOUT_USER: 'USERS/LOGOUT_USER',
  // Game
  SET_GAMES: 'GAME/SET_GAMES',
  GET_GAME_DETAIL: 'GAME/GET_DETAIL',
  // Topics
  SET_TOPICS: 'GAME/SET_TOPICS'
}
