export default {
  // User
  SET_USERS: 'USERS/SET_USERS',
  SET_AUTHUSER: 'USERS/SET_AUTHUSER',
  SET_CHILD: 'USERS/SET_CHILD',
  LOGOUT_USER: 'USERS/LOGOUT_USER',
  // Game
  SET_GAMES: 'GAME/SET_GAMES',
  // Topics
  SET_TOPICS: 'GAME/SET_TOPICS',
  // Class
  SET_SCHOOLCLASS: 'SCHOOLCLASS/SET_SCHOOLCLASS'
}
